### ISSUE TITLE
4.26 build?

### ISSUE THREAD

**Issue by Flynsarmy** [BenPyton/ProceduralDungeon#1]
Any chance this could get updated for 4.26? When I drop it into my project, UE attempts to rebuild and fails.

**Comment by BenPyton** [comment]
I have tested in a 4.25 project and works just fine.
I will test in a 4.26 project.

**Comment by BenPyton** [comment]
There you go : [this release should do the job](https://github.com/BenPyton/ProceduralDungeon/releases/tag/v1.0.2)
I will certainly do it also for the other unreal versions between.

**Comment by Flynsarmy** [comment]
Thanks!
