### ISSUE TITLE
Basic Logic not working properly

### ISSUE THREAD

**Issue by CuriousUser** [BenPyton/ProceduralDungeon#10]
First I'd like to say thank you for this awesome Plugin, however; I'm having difficulties making it work.

So I tried following the Wiki for creating a basic random dungeon and here is the result;
![{6DFDB6E9-3AC3-4009-84F2-1739261B148F} png](https://user-images.githubusercontent.com/80597994/160563397-aa10a0bb-184a-4bcd-bb6c-0769c478a235.jpg)

Now allow me to show you the logic I tried to put according to the tutorial in the wiki.

- **Variables in my dungeon Blueprint**

![{BAF51A54-0A24-4AC1-B493-5E0F3D6587CA} png](https://user-images.githubusercontent.com/80597994/160563742-4c6d8042-aef2-4c1b-bc6f-7cb96183557c.jpg)

- **Room Architecture**

I create a basic room with 1 door for the sake of simplicity and because the "Choose Door" Function allows putting doors between rooms according to my understanding
![{81444C26-9CE7-4FA6-9E6A-D969FFB323E6} png](https://user-images.githubusercontent.com/80597994/160564232-db54bb3e-f829-43e3-81a4-1ee2c8c6111d.jpg)

- **Choose Door**

![{E82462C8-906A-43E4-80DF-F811A52EED65} png](https://user-images.githubusercontent.com/80597994/160563870-8f131aa5-7f72-45c4-a885-82ec8c5804b6.jpg)

- **Choose First Room**

![{29FF35BE-8E94-4FFA-84FF-D7DC39A0C142} png](https://user-images.githubusercontent.com/80597994/160564767-3e247f7b-4949-4e3c-a5b4-a04280d5cb81.jpg)

- **Choose Next Room**

![{ED3AF951-7E98-447F-AA76-2FCAD31DA867} png](https://user-images.githubusercontent.com/80597994/160564961-bb7df5e7-27ed-4188-96f2-3959ca8f9812.jpg)

- **Continue to Add Room**

![{67047581-45AD-4BAC-B970-A05B57404CAA} png](https://user-images.githubusercontent.com/80597994/160565158-737280eb-ccda-4be8-af95-f0b7c1c0563b.jpg)

- **isValid Dungeon**

![{92C90B6F-49DE-4E9E-A8CA-4E386C2E3671} png](https://user-images.githubusercontent.com/80597994/160565279-0a3f53da-8043-4eb9-ac0d-12215f2d1e71.jpg)

- **Event Graph Logic**

![{642C6D7F-A2A4-4806-9BD7-DF8A0398078C} png](https://user-images.githubusercontent.com/80597994/160565596-0601cef4-215e-4d4a-9efd-574d3d90daa7.jpg)

If there is anything tat I've messed up please do let me know and thank you for reading.

**Technical informations**
 - OS: [e.g. Windows 10]
 - Specs: i7 4790K, 16GB RAM, Asus GTX 1080ti
 - Unreal: 4.26
 - Plugin Version: 2.0.1

**Comment by BenPyton** [comment]
Hello CuriousUser,

First of all, you understood very well how the plugin works :)

The issue you have is that your room doesn't have enough doors.
You're expecting your dungeon to be at least 4 rooms (from your _IsValidDungeon_)
But since you only have 1 type of room with 1 door only, it will generates **only** dungeons with 2 rooms (each one connected to the other with their unique door)

So you have to put at least one room with 2 doors in your _NormalRooms_ array to make it works.

Let me know if this resolves your issue ;)
I think I will add that statement in the wiki for future users.

Also, you should use _MinNbRoom_ in your _ContinueToAddRoom_ instead of the hardcoded _8_ to be consistent with your _ChooseNextRoom_. And you can replace the _Branch_ node by a _Not_ node that you connect directly in the _Return_ node in _ContinueToAddRoom_.

**Comment by CuriousUser** [comment]
Hello again, thanks for the answer.

- Here are the changes I brought, and now I have at least 6 rooms with various number of doors
![{568EFF5E-A4F0-41CD-BA82-93E3000F64CE} png](https://user-images.githubusercontent.com/80597994/160570938-37bb87e9-0f11-4db2-b88e-22a4f4672f81.jpg)
And now it's a mess, goes to infinity...
![{1DC5D62E-7CE4-42C8-AE49-49E1A888B98D} png](https://user-images.githubusercontent.com/80597994/160571334-8f73a2fb-2017-4247-884e-9a6663fa98ac.jpg)

**Comment by CuriousUser** [comment]
- I've put this in the logic in order to know the number of rooms

![{295963CE-5CAA-4422-ACA2-393EAA033D8E} png](https://user-images.githubusercontent.com/80597994/160572989-f983cbcb-e83e-49f5-955e-b0d4554b0df8.jpg)

- And here it shows that there are 0 rooms
-
![{896A339B-E8DD-438A-B4D8-47AE03BA0C11} png](https://user-images.githubusercontent.com/80597994/160573145-1fbcecf9-7d6f-443a-83bd-b6b56f94d1f7.jpg)

**Comment by BenPyton** [comment]
Okay...
Maybe there is an issue in your generation logic or in your variables values ?
I see a lot of PreGeneration print on your screenshot, so I suppose it can't generate a valid dungeon.

What if you put your NbRoom print in your _ContinueToAddRoom_ ?

**Comment by CuriousUser** [comment]
- Ok I'll show you all my variables real quick
**For the rooms Variables**
![{A79DEC73-8579-40C4-9BDB-3DD870BE47F6} png](https://user-images.githubusercontent.com/80597994/160574222-bcdce1aa-74f2-4788-b0e2-c90794293d47.jpg)
They are empty at start and only set on Event BeginPlay 
![{1A15A97F-18DC-454F-AF73-C90FF10F9216} png](https://user-images.githubusercontent.com/80597994/160574477-70424f34-b2df-4f4b-8484-1b9a721fc2e8.jpg)
**4 Seconds after that comes the generation**
![{CBFC7ECB-9D95-4EBC-A9E5-6BFE6F588999} png](https://user-images.githubusercontent.com/80597994/160574731-3eb489df-e1d4-4803-9a70-f87cfd4a146c.jpg)
**MinNbRooms** is set at 32 by default
![{59FE39C2-E7BC-4C8C-9952-94104B4E3D16} png](https://user-images.githubusercontent.com/80597994/160574932-3f7fe349-6cb7-488c-b2dd-bbf9aac2f37c.jpg)
**I'm taking Screenshots as soon as it shows numbers and then it starts freezing and goes to infinity**
![{FD2D741C-BE8A-47A4-8B53-B28F79EE3AAC} png](https://user-images.githubusercontent.com/80597994/160575555-8c3b6387-563c-473a-8d5d-c8261c64cbac.jpg)
**When I press Escape** this message pops
![{0EB8CFAA-8081-458C-B606-B7E8749DF2E5} png](https://user-images.githubusercontent.com/80597994/160575681-ddc8ef21-dd5c-42f0-bb00-8580a3b27411.jpg)
**This is Continue to Add Room**
![{D621121B-AF79-4C34-9056-C5CFAD166630} png](https://user-images.githubusercontent.com/80597994/160575955-a13a40ac-312c-48bf-b3ee-394f91f70018.jpg)
**This is Find Choose Next Room**
![{07E8CD68-9491-41C6-8C9C-EEE42774631D} png](https://user-images.githubusercontent.com/80597994/160576028-347777bd-32e4-4ffd-b9be-366f078eea3e.jpg)
The Errors seem to come from these 2 functions

**Comment by CuriousUser** [comment]
Ok then give me a moment and I'll share it on google drive is that cool?

**Comment by CuriousUser** [comment]
https://drive.google.com/file/d/1JuDKw84bl27YuJVOr3cGwt0CCO7LI6nl/view?usp=sharing

**Comment by BenPyton** [comment]
Thank you, I'll get back to you ASAP :)

**Comment by BenPyton** [comment]
Oh okay, I found the issue.
You need to create Levels for rooms.
Currently the dungeon instantiate himself inside of the level, and then do it infinitely.

**Comment by CuriousUser** [comment]
Are you talking about this ?
![{E394F14D-A6A5-454C-9B32-9AF0DAD478BA} png](https://user-images.githubusercontent.com/80597994/160601550-72f0d75d-ad3f-4ed5-8f60-d01f9d22ecfe.jpg)

**Comment by BenPyton** [comment]
Yes, exactly.
One room : one data and one level.
In the level blueprint you set the data, and in the data you set the level.

Then in a master level (not a room, so no reparenting to RoomLevelScriptActor this one) you place your DungeonGenerator that will load and instantiate the room levels inside the master level.

**Comment by CuriousUser** [comment]
I'd like to know why this door is in the middle of a room, all my room data has doors on the walls , there is no room that has a door in the middle otherwise it creates a big error from the start
![image](https://user-images.githubusercontent.com/80597994/160605770-cbbc83f6-074c-48ac-83e5-c5a3380c9c18.png)

**Comment by BenPyton** [comment]
> However the doors are a bit wonky, it shows 334 actors and I counted about 23 rooms yet I set the max to 8
I will investigate that.

> I'd like to know why this door is in the middle of a room
Do not take care of it, this is the door box of the doors themselves (they are all stacked on the same place)
The ones placed correctly on the doors are those from the rooms, so actually each door as 2 debug boxes drawn
I didn't found a way to not render them when not in the Blueprint previewer...

Anyway, those blue, red and pink lines are not drawn in shipping. (you can also desactivate them in the plugin settings)

**Comment by CuriousUser** [comment]
There's still the issue of the number of rooms, I'm asking for 4 maximum rooms, it's spawning hundreds in certain cases, you saw my conditions for continuing to spawn, the dungeon should stop when I have an end room and the dungeon is valid when I hit a number of rooms.

**Comment by BenPyton** [comment]
Since you changed your logic with a MaxNbRoom in your IsValidDungeon, you have to change the comparison too.
(it was good before because the hardcoded number you set here was lower than the MinNbRoom you defined)

![image](https://user-images.githubusercontent.com/13402355/160609954-b11079bd-8ecd-428c-a00b-79fd31cb40e6.png)

Also, you still have to make one level per room with their corresponding data set in the level blueprints.
It works fine for me (it generates 4 rooms before adding the ending room, then stops the generation)

![image](https://user-images.githubusercontent.com/13402355/160609281-01f645b7-e9c2-4387-8830-80af552620a5.png)

**Comment by BenPyton** [comment]
By the way, if you want to set a min and a max number of rooms, you should do it in the _ContinueToAddRoom_ and in the _IsValidDungeon_ (you can create a new function to factorize this condition)

![image](https://user-images.githubusercontent.com/13402355/160612076-becce243-23d3-45a5-b142-837c613df0d0.png)

![image](https://user-images.githubusercontent.com/13402355/160611811-1bdce006-65c5-490f-870a-15fd8156912c.png)

![image](https://user-images.githubusercontent.com/13402355/160611943-1defa214-41b6-4019-ae49-8c08ddd99887.png)

**Comment by CuriousUser** [comment]
I'll try what you just sent me

**Comment by BenPyton** [comment]
Good !

Remember, the lines are juste bounding boxes of the rooms (and just debug prints, not visible in the shipped game), you can do whatever you want inside, it is not mandatory to fill all the space inside.

You design your rooms in the room's levels, and do not place doors in the rooms, they are spawned separately.
In the room's levels, leave empty the spaces inside the blue boxes for the doors.

I'll close the issue now that it is solved ;)
