### ISSUE TITLE
[QUESTION] Top doors and trap doors.

### ISSUE THREAD

**Issue by mokargas** [BenPyton/ProceduralDungeon#14]
This is a question(s) more than a bug.

Is there anyway to modify the generator to create a trap door or roof positioned door. For instance, let's say I want a room generated on another level, but want an actor (say a lift or elevator rather than stairs) to push the player up into that room?

Similarily for trap doors that drop a player deeper into the dungeon (I think that would be a common use case).

**Comment by BenPyton** [comment]
Hello Mokargas,

The plugin doesn't support doors on floor/roof of the rooms.
It was once in my todo-list but I don't have the time to actively add new features to the plugin now (I prefer to keep it stable first)

However, you can add special rooms on 2 or more levels (Z size of the rooms) in which you place your elevators/trap doors.

You can also change the plugin's code to add this feature too if you want :)
(And maybe do a PR here to add your new feature)

Hope this answers your question.

**Comment by BenPyton** [comment]
Hello Mokargas,

Since it's been 1 week I didn't have any new comment here, I consider you have resolved your issue.
So, I close this issue as completed.

Best regards.
