### ISSUE TITLE
Question: Is there a way to despawn and respawn individual rooms

### ISSUE THREAD

**Issue by Andipog** [BenPyton/ProceduralDungeon#16]
I just wanted to know this, as I wanted rooms to despawn as the player moves through the level, but when they come back the rooms respawn.

**Comment by BenPyton** [comment]
Hi Andipog,

Currently, the plugin doesn't support room's despawn/respawn.

The simple occlusion culling I've implemented is just a visibility toggle of the static actors of the rooms.
I made that to keep the collisions of the hidden rooms so the pawns (like ennemies, etc.) can navigate outside of the player's room.

However, I think you can easily add the feature in the code : where I toggle the visibility of the rooms, you can instead load/unload the room's level instance.
But I don't know if it will reset the actors inside.

If you just want to reset the actors of previously visited rooms, you can use the room's player detection.
When the player enters, you would reset the actors like enemy spawners to respawn enemies for instance.
I can't check right now, but I think you can do that in pure blueprint.

I don't know if that answers you question. If not, feel free to explain more  what you want to do.

**Comment by Andipog** [comment]
Yes, I think you kind of answered the question, thanks, also how can I turn off the red box around each room? I think it's messing up reflections.

**Comment by BenPyton** [comment]
The red boxes are just a debug view, they are not displayed in packaged game for shipping.

You can disable them in the editor by unchecking the [`Draw Debug` field in the plugin settings](https://github.com/BenPyton/ProceduralDungeon/wiki/Plugin-Settings)
