### ISSUE TITLE
Critical Error when Compiling

### ISSUE THREAD

**Issue by Gagel82** [BenPyton/ProceduralDungeon#17]
12:688][  0]LogAndroid: Error: === Critical error: ===
LogPlayLevel: Error:   12-17 02:07:12.688 25504 25529 D UE4     : [2022.12.17-07.07.12:688][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-17 02:07:12.688 25504 25529 D UE4     : [2022.12.17-07.07.12:688][  0]LogAndroid: Error: Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/Serialization/AsyncLoading.cpp] [Line: 3159]
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:688][  0]LogAndroid: Error: Could not find SuperStruct OnDoorClose_BP to create OnDoorClose_BP
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A18CC4 libUE4.so(0x0000000007B58CC4)![Unknown]()  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A18A60 libUE4.so(0x0000000007B58A60)!FAsyncPackage::EventDrivenSerializeExport(int)  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A1210C libUE4.so(0x0000000007B5210C)!FAsyncPackage::ProcessImportsAndExports_Event()  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A118E0 libUE4.so(0x0000000007B518E0)!FAsyncPackage::Event_ProcessImportsAndExports()  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A1F338 libUE4.so(0x0000000007B5F338)!FAsyncLoadingThread::ProcessAsyncLoading(int&, bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A28AB8 libUE4.so(0x0000000007B68AB8)!FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*)  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A27F60 libUE4.so(0x0000000007B67F60)!FAsyncLoadingThread::TickAsyncLoading(bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A390D0 libUE4.so(0x0000000007B790D0)!FAsyncLoadingThread::FlushLoading(int)  []
LogPlayLevel: Error:   12-17 02:07:12.689 25504 25529 D UE4     : [2022.12.17-07.07.12:689][  0]LogAndroid: Error: [Callstack] 0x00000000B6A9A5A4 libUE4.so(0x0000000007BDA5A4)!FlushAsyncLoading(int)  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000B6D49794 libUE4.so(0x0000000007E89794)!LoadPackageInternal(UPackage*, char16_t const*, unsigned int, FLinkerLoad*, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000B6D47330 libUE4.so(0x0000000007E87330)!LoadPackage(UPackage*, char16_t const*, unsigned int, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000BB1270FC libUE4.so(0x000000000C2670FC)!UEngine::LoadMap(FWorldContext&, FURL, UPendingNetGame*, FString&)  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000BB121C84 libUE4.so(0x000000000C261C84)!UEngine::Browse(FWorldContext&, FURL, FString&)  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000BA5B4FF4 libUE4.so(0x000000000B6F4FF4)!UGameInstance::StartGameInstance()  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000B4EE3164 libUE4.so(0x0000000006023164)!FEngineLoop::Init()  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000B4EE1C98 libUE4.so(0x0000000006021C98)!AndroidMain(android_app*)  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000B4EF535C libUE4.so(0x000000000603535C)!android_main()  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000B4F2B910 libUE4.so(0x000000000606B910)![Unknown]()  []
LogPlayLevel: Error:   12-17 02:07:12.690 25504 25529 D UE4     : [2022.12.17-07.07.12:690][  0]LogAndroid: Error: [Callstack] 0x00000000E601B6D6 libc.so(0x000000000009A6D6)![Unknown]()  []
LogPlayLevel: Error:   12-17 02:07:12.691 25504 25529 D UE4     : [2022.12.17-07.07.12:691][  0]LogAndroid: Error: [Callstack] 0x00000000E5FE0278 libc.so(0x000000000005F278)![Unknown]()  []
LogPlayLevel: Error:   12-17 02:07:12.691 25504 25529 D UE4     : [2022.12.17-07.07.12:691][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-17 02:07:12.691 25504 25529 D UE4     : [2022.12.17-07.07.12:691][  0]LogAndroid: Error:

**Comment by Gagel82** [comment]
I wanted to add that your hard work is appreciated and your plug-in is amazing!  Gor context I'm working on small VR project and tried converting to c++ to resolve above error with no joy.  I will try fresh compile / build tomorrow and let you know results. Thanks so much for your time.

**Comment by BenPyton** [comment]
Hi Gagel82,

I need more info on your compilation context.

What plugin version are you using?
What Unreal engine version?
Are you trying to compile for Android?
Blueprint or C++ project?
Shipping or debug build?

Best regards.

**Comment by Gagel82** [comment]
I went back to before plugin (only having a working VR pawn) and it compiled fine.  However, as soon as I try to use the plugin....I get the compile errors. 

Info:

ProceduralDungeon_v2.0.2_UE4.27.zip
Unreal 4.27
Android (For oculus quest 2).
Blueprint
Debug build
Compiles with plugin "enabled" and works fine in VR, but as soon as I compile with the "ExampleGenerator" BP in the level, I get the following error in compile.
This is with no further changes other than setting default map to master level and choosing the example game mode provided in your example project.
Works fine in VR Preview as well.

LogPlayLevel: Error:   12-18 13:37:50.720 10754 10789 D UE4     : [2022.12.18-18.37.50:720][  0]LogAndroid: Error: === Critical error: ===
LogPlayLevel: Error:   12-18 13:37:50.720 10754 10789 D UE4     : [2022.12.18-18.37.50:720][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-18 13:37:50.720 10754 10789 D UE4     : [2022.12.18-18.37.50:720][  0]LogAndroid: Error: Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/Serialization/AsyncLoading.cpp] [Line: 3159]
LogPlayLevel: Error:   12-18 13:37:50.720 10754 10789 D UE4     : [2022.12.18-18.37.50:720][  0]LogAndroid: Error: Could not find SuperStruct Door to create Wall_C
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E18504 libUE4.so(0x0000000007B57504)![Unknown]()  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E182A0 libUE4.so(0x0000000007B572A0)!FAsyncPackage::EventDrivenSerializeExport(int)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E1194C libUE4.so(0x0000000007B5094C)!FAsyncPackage::ProcessImportsAndExports_Event()  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E11120 libUE4.so(0x0000000007B50120)!FAsyncPackage::Event_ProcessImportsAndExports()  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E1EB78 libUE4.so(0x0000000007B5DB78)!FAsyncLoadingThread::ProcessAsyncLoading(int&, bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E282F8 libUE4.so(0x0000000007B672F8)!FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E277A0 libUE4.so(0x0000000007B667A0)!FAsyncLoadingThread::TickAsyncLoading(bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E38910 libUE4.so(0x0000000007B77910)!FAsyncLoadingThread::FlushLoading(int)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B5E99DE4 libUE4.so(0x0000000007BD8DE4)!FlushAsyncLoading(int)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B6148FD4 libUE4.so(0x0000000007E87FD4)!LoadPackageInternal(UPackage*, char16_t const*, unsigned int, FLinkerLoad*, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B6146B70 libUE4.so(0x0000000007E85B70)!LoadPackage(UPackage*, char16_t const*, unsigned int, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000BA52693C libUE4.so(0x000000000C26593C)!UEngine::LoadMap(FWorldContext&, FURL, UPendingNetGame*, FString&)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000BA5214C4 libUE4.so(0x000000000C2604C4)!UEngine::Browse(FWorldContext&, FURL, FString&)  []
LogPlayLevel: Error:   12-18 13:37:50.721 10754 10789 D UE4     : [2022.12.18-18.37.50:721][  0]LogAndroid: Error: [Callstack] 0x00000000B99B4834 libUE4.so(0x000000000B6F3834)!UGameInstance::StartGameInstance()  []
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error: [Callstack] 0x00000000B42E3164 libUE4.so(0x0000000006022164)!FEngineLoop::Init()  []
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error: [Callstack] 0x00000000B42E1C98 libUE4.so(0x0000000006020C98)!AndroidMain(android_app*)  []
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error: [Callstack] 0x00000000B42F535C libUE4.so(0x000000000603435C)!android_main()  []
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error: [Callstack] 0x00000000B432B910 libUE4.so(0x000000000606A910)![Unknown]()  []
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error: [Callstack] 0x00000000E601B6D6 libc.so(0x000000000009A6D6)![Unknown]()  []
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error: [Callstack] 0x00000000E5FE0278 libc.so(0x000000000005F278)![Unknown]()  []
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-18 13:37:50.722 10754 10789 D UE4     : [2022.12.18-18.37.50:722][  0]LogAndroid: Error:

**Comment by Gagel82** [comment]
After rebuilding from scratch, not using example template, I get the following:

LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: === Critical error: ===
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/Serialization/AsyncLoading.cpp] [Line: 3159]
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: Could not find SuperStruct OnPostGeneration_BP to create OnPostGeneration_BP
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: [Callstack] 0x00000000B6758504 libUE4.so(0x0000000007B57504)![Unknown]()  []
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: [Callstack] 0x00000000B67582A0 libUE4.so(0x0000000007B572A0)!FAsyncPackage::EventDrivenSerializeExport(int)  []
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: [Callstack] 0x00000000B675194C libUE4.so(0x0000000007B5094C)!FAsyncPackage::ProcessImportsAndExports_Event()  []
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: [Callstack] 0x00000000B6751120 libUE4.so(0x0000000007B50120)!FAsyncPackage::Event_ProcessImportsAndExports()  []
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: [Callstack] 0x00000000B675EB78 libUE4.so(0x0000000007B5DB78)!FAsyncLoadingThread::ProcessAsyncLoading(int&, bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: [Callstack] 0x00000000B67682F8 libUE4.so(0x0000000007B672F8)!FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*)  []
LogPlayLevel: Error:   12-18 14:40:13.343 13320 13354 D UE4     : [2022.12.18-19.40.13:343][  0]LogAndroid: Error: [Callstack] 0x00000000B67677A0 libUE4.so(0x0000000007B667A0)!FAsyncLoadingThread::TickAsyncLoading(bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B6778910 libUE4.so(0x0000000007B77910)!FAsyncLoadingThread::FlushLoading(int)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B67D9DE4 libUE4.so(0x0000000007BD8DE4)!FlushAsyncLoading(int)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B6A88FD4 libUE4.so(0x0000000007E87FD4)!LoadPackageInternal(UPackage*, char16_t const*, unsigned int, FLinkerLoad*, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B6A86B70 libUE4.so(0x0000000007E85B70)!LoadPackage(UPackage*, char16_t const*, unsigned int, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000BAE6693C libUE4.so(0x000000000C26593C)!UEngine::LoadMap(FWorldContext&, FURL, UPendingNetGame*, FString&)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000BAE614C4 libUE4.so(0x000000000C2604C4)!UEngine::Browse(FWorldContext&, FURL, FString&)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000BA2F4834 libUE4.so(0x000000000B6F3834)!UGameInstance::StartGameInstance()  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B4C23164 libUE4.so(0x0000000006022164)!FEngineLoop::Init()  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B4C21C98 libUE4.so(0x0000000006020C98)!AndroidMain(android_app*)  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B4C3535C libUE4.so(0x000000000603435C)!android_main()  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000B4C6B910 libUE4.so(0x000000000606A910)![Unknown]()  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000E601B6D6 libc.so(0x000000000009A6D6)![Unknown]()  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error: [Callstack] 0x00000000E5FE0278 libc.so(0x000000000005F278)![Unknown]()  []
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-18 14:40:13.344 13320 13354 D UE4     : [2022.12.18-19.40.13:344][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-18 14:40:13.345 13320 13354 D UE4     : [2022.12.18-19.40.13:345][  0]LogAndroid: Error:

**Comment by BenPyton** [comment]
Actually, I have never compiled the plugin for Android. Since your project is pure blueprint, I think the compiler can't use the precompiled plugin.

I didn't understand well in your first post if you have tried to setup a C++ project.
I think you have to convert your project to C++ (try a test on the sample project first) and add the plugin sources in the `Plugins` folder of the project.
Then compile it.

If this is working, you could also try to package the plugin for Android in the test project, then install it in the engine to be able to use it in your blueprint project.

I didn't tested that, but if it works for you, then I will do that also to publish the Android build.

If that does not work, then I will spend more time on that issue when I have some free time in the next days.

Best regards.

**Comment by Gagel82** [comment]
Example Project:
 - Loads in preview
 - Plays in preview
 - Converted to C++ by adding new class
 - Generated Project Files
 - Added plugin folder to project directory
 - Compiled in Visual Studio 2019
 Issue Persists, same messages about not able to find Superstruct
Attempted again (thinking it could be a VR Template issue).  Created VR project, migrated example project files, set game mode/maps and modes accordingly.  Launched to Android.
Issue still Persists.

I understand busy schedules and appreciate any time you allot to this process.  Thanks so much!

**Comment by Gagel82** [comment]
Seems to be different superstructs on each compile that throw the error? 

Latest Log. 
LogPlayLevel: Error:   12-18 17:39:35.933 21591 21621 D UE4     : [2022.12.18-22.39.35:933][  0]LogAndroid: Error: === Critical error: ===
LogPlayLevel: Error:   12-18 17:39:35.933 21591 21621 D UE4     : [2022.12.18-22.39.35:933][  0]LogAndroid: Error:
LogPlayLevel: Error:   12-18 17:39:35.934 21591 21621 D UE4     : [2022.12.18-22.39.35:933][  0]LogAndroid: Error: Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/Serialization/AsyncLoading.cpp] [Line: 3159]
LogPlayLevel: Error:   12-18 17:39:35.934 21591 21621 D UE4     : [2022.12.18-22.39.35:934][  0]LogAndroid: Error: Could not find SuperStruct RoomData to create ExampleRoomData_C

**Comment by Gagel82** [comment]
Sorry for spam :(  I wanted to let you know that I verified my  Visual Studio is also set up correctly and I am able to compile my project with other C++ plugins installed to the android with no issue (I tried out an UpperBody IK program that is neat) But I digress, the code will compile, and launch with the dungeon generator plugin, but as soon as I put a generator in the world, it only works in VR preview.  When compiling, it gets the issues with asyncloading and superstructs.

**Comment by BenPyton** [comment]
I can't setup the Android environment right now to test it myself (I should be able in January I think).
In the meantime, I have some ideas to help you.
In your C++ test project, open the `YourProject/Plugins/ProceduralDungeon/ProceduralDungeon.uplugin` file in any text editor.

First, try to change the `LoadingPhase` in the `Modules` from `PreDefault` to `Default`. Maybe your issue is a loading order issue of the plugin.

If it does not work, try to remove the `WhitelistPlatforms` array in this file (and the coma on the previous line too) like this :
```
	"Modules": [
		{
			"Name": "ProceduralDungeon",
			"Type": "Runtime",
			"LoadingPhase": "Default"
		}
	]
```
This should make the plugin setup like `UpperBody IK` plugin which is working for you.

As I said, I will not be able to have the time to setup the Android environment before january. 
So I can't debug it myself at this time...

Best regads.

**Comment by BenPyton** [comment]
Hi Gagel82,

Glad to see that solution worked for you :)

Did you test with the `Default` only? Was it not enough to solve the issue?

I will update the plugin when I have some times, so other people will not run to this issue anymore.

I hope your game will reach the production!

Best regards.

**Comment by Gagel82** [comment]
Yes , default only did not solve and was discouraging, but after clearing
the white list we are in the clear.  I guess inwont sleep for weeks!
Thanks so much again Ben!

**Comment by BenPyton** [comment]
I would like to know if the `Default` was necessary.

Can you try a last atempt please with the 'Default' set back to 'PreDefault`?
(With the whitelist removed of course)

I don't remember why I set to 'PreDefault', but it certainly was important...

Best regards.
