### ISSUE TITLE
Question: Where do the functions go

### ISSUE THREAD

**Issue by jiggensnaggen** [BenPyton/ProceduralDungeon#19]
Question. Where does the blueprint logic go? Where do i put the functions?

**Comment by jiggensnaggen** [comment]
on the wiki page named :Choose First Room Data
it is not specific where to implement the function. I notice its overridable in the dungeon generator class but thats not what i have made. i only have the room and data asset for the room made. do i put these functions in one of those? can you please assist?

**Comment by BenPyton** [comment]
Hi jiggensnaggen,

You need to create a [Dungeon Generator](https://github.com/BenPyton/ProceduralDungeon/wiki/Dungeon-Generator#create-a-dungeon-generator) actor and place it in your master level.

This is where the logic goes and where you override the functions mentioned in the wiki.

The master level is a regular level, not a room with a rool data.

Best regards.

**Comment by jiggensnaggen** [comment]
> Hi jiggensnaggen,
> 
> You need to create a [Dungeon Generator](https://github.com/BenPyton/ProceduralDungeon/wiki/Dungeon-Generator#create-a-dungeon-generator) actor and place it in your master level.
> 
> This is where the logic goes and where you override the functions mentioned in the wiki.
> 
> The master level is a regular level, not a room with a rool data.
> 
> Best regards.

Where do we get the variables needed? how do i get my room data into the dungeon generator to plug into choose first room?

**Comment by jiggensnaggen** [comment]
I think i figured it out. Do i just make a new variable and set its default value to the data asset i made?

**Comment by jiggensnaggen** [comment]
In the choose door function, where do we get this wall class? same with normal door. I only have door

**Comment by jiggensnaggen** [comment]
I got a dungeon to generate. But i just made the wall another door. I am seeing no walls, floor, or ceiling. How do i add these?

**Comment by BenPyton** [comment]
Hi jiggensnaggen,

1- You have to create the variables you want in your dungeon generator blueprint, and set their default values or their values in the instances in your levels.

2- The normal door and wall are just child blueprints of door class, with different meshes (one with a door that opens and closes with a trigger box, and another with just a cube blocking the way).

3- You have to design your rooms individually by placing all static meshes (floor, ceils, walls, etc.) you want in the room levels. To see the entire dungeon in PIE, you can disable the occlusion culling system in the [plugin's settings](https://github.com/BenPyton/ProceduralDungeon/wiki/Plugin-Settings#plugin-settings).

Best regards.
