### ISSUE TITLE
Is it possible to offset the starting room?

### ISSUE THREAD

**Issue by SAM2WOW** [BenPyton/ProceduralDungeon#28]
Hello!

I'm wondering if it's possible to spawn the first room in a different location than the origin?

I'm trying to make a continuous procedural level where I want to generate the next set of rooms from where the end room of the previous generation is at. 

Thank you!

**Comment by BenPyton** [comment]
Hi @SAM2WOW 

Yes it is possible.
You just have to enable the `Use Generator Transform` in your `DungeonGenerator` actor and place it where you want your starting room.
([this issue](#15) is when I implemented the feature)

P.S.: I noticed that it is not documented in the wiki, I will update it when I have some times.

Best.

**Comment by SAM2WOW** [comment]
Oh yes! I haven't got to try the generator transform but I think I understand how it works. Thank you so much for the update!

On that note, I do have another question. Is it possible to generate again without deleting the previous generation?

**Comment by SAM2WOW** [comment]
Ah, that is indeed what I'm trying to do. And Thank you so much!
