### ISSUE TITLE
Engine Crashes during Generation

### ISSUE THREAD

**Issue by RedEnderman19** [BenPyton/ProceduralDungeon#3]
Each time I call the Generate Function from the Event Graph of the Dungeon Generator Blueprint, the Engine Crashes.

Im new in Unreal Engine and dont understand what is going wrong... HELP.... PLEAAAASE...

**Comment by BenPyton** [comment]
Can you provide more details, please ?
- What UE4 engine version do you use ?
- What plugin version do you use ?
- Did you follow [the wiki I wrote](https://github.com/BenPyton/ProceduralDungeon/wiki) to define all the needed functions for the plugin to work ?
- Can you provide the crash log ?

**Comment by RedEnderman19** [comment]
I use the newest Engine version and the newest Plugin version.

I followed the wiki exactly.

Link to Crashreport: https://pastebin.com/xiYb47zi

**Comment by BenPyton** [comment]
When you say newest, you mean UE4.26 ? with the plugin built for 4.26 too ? (to be sure)
The log says it crashed when starting the generation, I will investigate that when I'm home.

**Comment by RedEnderman19** [comment]
Yes im Using 4.26 on Unreal Engine and the Plugin

**Comment by RedEnderman19** [comment]
I tried it 50 times and it crashed 38 times in total

**Comment by RedEnderman19** [comment]
I spawned under the map at the remaining 12 times

**Comment by RedEnderman19** [comment]
It tried a few times... with 5 rooms it crashed 2/3 of the time.
with 20 rooms it crashed all the time

**Comment by BenPyton** [comment]
Can you provide a minimal repro project ?

P.S. : Please, edit your last comment if you add informations to it, instead of creating a new comment each time. It spam my mailbox...

**Comment by RedEnderman19** [comment]
The Link for the Project: https://drive.google.com/drive/folders/1HnduSGptEJyflwG-_xZfXLUqk8dMatAB?usp=sharing

Uploading took for EVER!!!

**Comment by BenPyton** [comment]
Ok, it is not really what I call a minimal repro (it has too many useless plugins for the repro, and since its size is 9 GB, it's obvious it takes an eternity to upload)
However, I can reproduce your crash and I will investigate it.
I will come back to you when I have managed to fix this crash.

**Comment by BenPyton** [comment]
Ok, I found the bug and released a new version of the plugin.
Thank you for reporting this issue :)

I added somes tips at the end of [the `Home` page of the wiki](https://github.com/BenPyton/ProceduralDungeon/wiki) for your issue with the character being under the map after the dungeon generation.

**Comment by RedEnderman19** [comment]
I can dont find any informations in the entire internet of how to delay player spawning or teleporting him to my playerspawn.

My playerspawn is in the Startingroom Blueprint and i dont can find any way of getting his position from the Post-Generation function

**Comment by BenPyton** [comment]
This is off topic of this plugin.
I do a simple search with "UE4 delay player spawn" on google and [the first link I found](https://forums.unrealengine.com/development-discussion/c-gameplay-programming/21223-spawn-player-manually-delay-player-spawn) gives a solution on post #4.

If you have some other questions about how to do this or that on UE4, please search UE forums or StackOverflow first.
And if you can't find your question there then post a question on those forums instead of here.
