### ISSUE TITLE
[BUG] cant compile for 5.3

### ISSUE THREAD

**Issue by GamesAndBacon** [BenPyton/ProceduralDungeon#35]
**Bug Description**
when trying to compile for 5.3 i get a weird syntax error for your DungeonEd_LogInfo
![image](https://github.com/BenPyton/ProceduralDungeon/assets/534830/d779f66c-e7b7-4bdb-8a58-21a799d0cebb)
i figured, hey its just log info, lets comment them out and now worries. 
which then lead to more errors. 
![image](https://github.com/BenPyton/ProceduralDungeon/assets/534830/6ce8c14d-fb81-4c35-a17e-743d6f7817c6)

im still learning a lot of my C++ and compilation errors are not a strong suit of mine :( sorry if perhaps this is quite simple. 

**Technical informations**
 - OS:. Windows 10
 - Unreal: 5.3
 - Plugin Version: 3.0

**Steps To Reproduce**
try to compile for 5.3 :) 

**Expected behavior**
compilation

**Comment by BenPyton** [comment]
Hi @GamesAndBacon 

Thank you for your report!

I have just downloaded 5.3 and I am not able to compile either.

I will fix that asap and publish the 3.0 version for UE 5.3.

Best regards.

**Comment by GamesAndBacon** [comment]
fantastic thank you. i had a few compilation errors from other plugins but usually managed to solve them. hope its not too much work :)

**Comment by BenPyton** [comment]
Hi @GamesAndBacon 

I have fixed compilation issues on my side for UE 5.3. I am able to package the plugin for 5.3 now.

Can you try with the code from the branch `Fix-UE5.3` on your side and tell me if it resolves your issues too?

Best regards.

**Comment by GamesAndBacon** [comment]
compiles for 5.3 ! thank you very much for the fix. looks like it wasnt entirely straight forward.
