### ISSUE TITLE
Changing to third person mode

### ISSUE THREAD

**Issue by Faulkbeets** [BenPyton/ProceduralDungeon#37]
How would I change this from fps to third person?

**Comment by BenPyton** [comment]
Hi @Faulkbeets 

I don't really understand your question...
There is no "FPS" or "third person" concepts in this plugin.

If you talk about the [dungeon example](https://github.com/BenPyton/DungeonExample), then you should first try to follow tutorials to learn the basics of Unreal Engine (like [creating a character](https://docs.unrealengine.com/5.0/en-US/setting-up-a-character-in-unreal-engine/)).

Then, if you have an issue with the dungeon example project, then please open your issue ticket in its repo, not here.

Also, keep in mind this is not a forum or a discussion place about Unreal Engine. You should only report bugs or issues related to the repo.

Best regards.

**Comment by Faulkbeets** [comment]
Thank you for your response. I meant when you run the example it's in first person, and I wanted to change it over to a third person camera style instead. I'll look into unreal forums shortly
