### ISSUE TITLE
All Rooms generate in 1 Line

### ISSUE THREAD

**Issue by RedEnderman19** [BenPyton/ProceduralDungeon#4]
I generated Dungeon with 10, 30 ,100 and 300 Rooms and each time the Rooms generated in 1 Line with a few single rooms on the sides. 

I have multiple Rooms with 3 Doors and they generate each time with 1 or 2 Deadends in that Room, or only Deadends in the next room.

Screenshot: https://drive.google.com/file/d/1AwU63xFiarDE6NjsMX5bU1hPZsP_2_sy/view?usp=sharing

**Comment by BenPyton** [comment]
Yes, I know this limitation of my plugin.
When I fixed your crash yesterday I saw that I can add the possibilty to make the dungeon more linear (currently what you have, giving priority to fill the doors of the last generated rooms) or more wide (giving priority to fill the doors of the first generated rooms).
I will try asap to add an option in the plugin settings to choose one or the other result.

In the meantime, what you can do to work around this is to define an end room with only one door, and after some number of generated room, you place this room (not another random door).
Then, you can continue to generate rooms after that to fill the deadends from the rooms before.
This is what I did in the project where I've developped this plugin.
