### ISSUE TITLE
Randon crash when generating dungeon

### ISSUE THREAD

**Issue by originalred** [BenPyton/ProceduralDungeon#44]
**Bug Description**
Randomly crashing when generating dungeon

**Technical informations**
 - OS: Windows 11
 - Unreal: 5.3.2
 - Plugin Version: 3.1.1

**Steps To Reproduce**
Randomly happens, usually on a 2nd editor run.

**Expected behavior**
Not randomly crashing

**Stack trace**
Assertion failed: Index >= 0 && Index < Connections.Num() [File:R:\ProceduraDungeon\Packaged\5.3\ProceduralDungeon\HostProject\Plugins\ProceduralDungeon\Source\ProceduralDungeon\Prvate\Room.cpp] [Line: 92]

UnrealEditor_ProceduralDungeon!ARoomLevel::Tick() [R:\ProceduralDungeon\Packaged\5.3\ProceduralDungeon\HostProject\Plugins\ProceduralDungeon\Source\ProceduralDungeon\Private\RoomLevel.cpp:165]

**Comment by BenPyton** [comment]
Hi @originalred 
It seems the room level and the room instance have their room data mismatching. And both data files have not the same amount of doors.

Can you share (if there is no sensible data) the output log please? Or read it by yourslef to check for an error?
There should be an error saying which rool level and instance have their data mismatching. (Meaning the level referenced in the room data is referencing this very same room data).

**Comment by originalred** [comment]
Many thanks.  I think I've found the issue - seems one of my levels wasn't configured properly and I'd accidentally deleted a couple of the levels in the list (and the room data was pointing to a different level).  

It seems stable (for now), but so far this issue can be closed.

**Comment by BenPyton** [comment]
Great to hear you fixed your issue!
I will fix the crash and make sure only error messages will be displayed instead.

**Comment by BenPyton** [comment]
The crash has been fixed in plugin version 3.1.2 (commit f259a78).
