### ISSUE TITLE
[BUG]LogError

### ISSUE THREAD

**Issue by Microquantus** [BenPyton/ProceduralDungeon#47]
![image](https://github.com/BenPyton/ProceduralDungeon/assets/134600386/12a34858-b13e-4cca-afcd-36b129fdc6aa)

**Comment by BenPyton** [comment]
Hi @Microquantus 
I will not be able to help you with just a screenshot.
Please add bug details by following the issue template.

**Comment by Microquantus** [comment]
struct FMargin3D need
