### ISSUE TITLE
Multiplayer Problems

### ISSUE THREAD

**Issue by RedEnderman19** [BenPyton/ProceduralDungeon#5]
I done every step from the wiki for multiplayer and created a startroom, which the players spawn in.

In this Room is an Door that teleports all players to the Map with the dungeon generator...

but they never land in the same Dungeon. Also they cannot see each others in the Dungeon, but they can in the Starting Room

**Comment by BenPyton** [comment]
I don't know well how to use network in UE4, but from what you have described I suppose there is something wrong with your travel from your starting (connection lobby?) map to the dungeon map (since the players did not see each other).

About the plugin, I suggest you to wait for all players to have fully travelled to the dungeon map before calling the Generate function from the DungeonGenerator.

**Comment by RedEnderman19** [comment]
I tried by best but i don't can get it to work...

Now both Players are stuck in the Void for ever and the Dungeon never Generates.

Screenshot of my Function: https://drive.google.com/file/d/1Gi4NobxlqNQIWe_-UBeMfd8wLH-aLJzN/view?usp=sharing

**Comment by BenPyton** [comment]
As I said, before trying to use the procedural generation, make sure your multiplayer works.
You can place a big plane in your map, where all the players are teleported. Then, make sure they seee each other and they are properly replicated (movements and actions of each are seen by the others).
If you struggle with that part, I will be no help for you. Try searching for tutorials, StackOveflow and the UE forums to make it to work.

Once you have checked this is working correctly, then you have to detect when all players are in your map before calling the Generate function.
You do it currently in the BeginPlay of the DungeonGenerator. This will check once when the DungeonGenerator is created (so before any player has arrived in the map). This for sure will never works.
I am not an expert in UE4 multiplayer, but I suggest you to search for an event like OnPostLogin (I don't know if this is triggered when travelling to a new map).
For instance, you can do this check in your LevelBlueprint: each time a player arrives in the map, you check if the number of player currently in your map correspond to the total number of player connected to your session.
If so you can call the Generate function on the DungeonGenerator.

**Comment by BenPyton** [comment]
Since you haven't updated this issue for a long time, I assume it is fixed on your side.
I close it.
