### ISSUE TITLE
Unreal Engine 5.5 support

### ISSUE THREAD

**Issue by encrystudio** [BenPyton/ProceduralDungeon#59]
Unreal Engine 5.5 released with several improvements. It would be cool if this plugin supports the new version. THank you for your work!

**Comment by BenPyton** [comment]
Yeah I'll work on it when I have some free time! 😉

**Comment by BenPyton** [comment]
Yes, I've made a commit in the branch `patches`.
I need to build in all other UE versions too.
The fixed version will be published soon.

**Comment by encrystudio** [comment]
Thank you 👍🏻
