### ISSUE TITLE
Packaging Issues

### ISSUE THREAD

**Issue by Clackroe** [BenPyton/ProceduralDungeon#6]
Hello! I have been working on a game for the past 2 weeks for a competition that I am in. I am using your plugin in my game and would love to allow others to play my game. However, when I try to package the game it comes up with many errors. The errors are posted below, do you have any idea how to fix this?

UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/ProceduralDungeonTypes.h(53) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/ProceduralDungeonTypes.h(55) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/Door.h(74) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/Door.h(77) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/DungeonGenerator.h(37) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/DungeonGenerator.h(83) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/DungeonGenerator.h(87) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/DungeonGenerator.h(91) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/DungeonGenerator.h(95) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/DungeonGenerator.h(99) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/DungeonGenerator.h(102) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/ProceduralLevelStreaming.h(66) : LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/RoomLevel.h(35) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/RoomLevel.h(50) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/TriggerType.h(30) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/TriggerType.h(32) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/TriggerType.h(34) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/TriggerType.h(37) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/TriggerType.h(60) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)):   D:/Unreal Engine/VERSIONS/UE_4.26/Engine/Plugins/ProceduralDungeon/Source/ProceduralDungeon/Public/TriggerType.h(63) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: Packaging (Windows (64-bit)): Took 4.623046s to run UnrealBuildTool.exe, ExitCode=6

**Comment by BenPyton** [comment]
Hello !
First, thank you to use my plugin !

It seems that I missed some things in code to make the plugin usable when it is installed in the Engine.
Try to put the plugin in the `Plugins` folder of your project instead of directly inside the Engine install folder.
Like this: `YourProject/Plugins/ProceduralDungeon` (and inside this folder there are `Binaries`, `Config`, `Source`, etc.)

Let me know if this workaround works for you :)

I will update the plugin ASAP when I have some free time to fix this issue.

**Comment by Clackroe** [comment]
You are very welcome! Your plugin has been extremely useful, and helped me accomplish what I wanted.

I will definitely try this solution as soon as I can, and will let you know if something goes wrong. 

Thank you!

**Comment by Clackroe** [comment]
Thank you for your help! I'm sorry to keep coming back with problems, but I have another problem. When I packaged the game after moving the plugin to the project itself, it packaged fine but when I tried to open it I got this error.

![Screenshot 2021-04-13 084807](https://user-images.githubusercontent.com/65436489/114556418-b001b100-9c36-11eb-9f13-7faa6b62a59c.png)

So then I thought that maybe I should enable Blueprint Nativization, and when I did that the packaging failed with this error.

![Screenshot 2021-04-13 085847](https://user-images.githubusercontent.com/65436489/114556517-ca3b8f00-9c36-11eb-8452-f86e71b5195d.png)

Do you have any suggestions on what I should do?

**Comment by BenPyton** [comment]
Is it a blueprint or a C++ project ?
If it is a blueprint project, then I can suggest you to install Visual Studio 2019, and create a C++ class in the UnrealEditor to update your project into a C++ project.

Let me know if this does not work for you.
I will test ASAP to package the plugin in a blueprint project.

**Comment by Clackroe** [comment]
Thank you! That worked. I appreciate all of your help, you have been more than kind.

**Comment by BenPyton** [comment]
I updated the plugin (v1.2.1) with a fix of the packaging errors when the plugin is installed in the engine.
Now the plugin can be used with blueprint only projects :)

Thank you for reporting this issue!
