### ISSUE TITLE
Crashing when generating

### ISSUE THREAD

**Issue by WiseMatthack** [BenPyton/ProceduralDungeon#7]
When trying to generate a level, UE4 crashes and prints out this log :

```Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000158

UE4Editor_ProceduralDungeon!ADungeonGenerator::OnStateTick() [R:\PD Packages\4_26\ProceduralDungeon\HostProject\Plugins\ProceduralDungeon\Source\ProceduralDungeon\Private\DungeonGenerator.cpp:418]
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll```

**Comment by BenPyton** [comment]
Hello WiseMatthack,

Can you provide more informations please ?
- The UE4 version you are using
- The plugin version you are using (and make sure you have the one matching your UE4 version)
- The configuration in Blueprint of your DungeonGenerator.

Also, did you managed to implement your generation logic ? (about your post before the edit)

**Comment by WiseMatthack** [comment]
Hey, thanks for your quick answer
Yes, I did manage to implement the generation logic! I didn't read the documentation carefully enough.
I'm using UE4 version 4.26.2, I'm using the latest version of the plugin (1.2.1) that is matching my UE4 version.
Just in case, here are my 3 rooms, each one has its own data file assigned:
First room:
![image](https://user-images.githubusercontent.com/32242507/122602951-f0850d00-d073-11eb-9c8c-fbc6a1e04dd3.png)

Second room:
![image](https://user-images.githubusercontent.com/32242507/122603052-14e0e980-d074-11eb-9877-39f35134845d.png)

Third room:
![image](https://user-images.githubusercontent.com/32242507/122603088-22966f00-d074-11eb-842e-e0a6552876cc.png)

There is a starting level where the player (on a cube so as not to fall), as well as the blueprint DungeonGenerator actor are.
![image](https://user-images.githubusercontent.com/32242507/122603876-62aa2180-d075-11eb-8faa-c4f8f0f88db6.png)

Here is the configuration of my DungeonGenerator:
![image](https://user-images.githubusercontent.com/32242507/122604026-95ecb080-d075-11eb-8e76-891b8805feb9.png)
![image](https://user-images.githubusercontent.com/32242507/122604053-9f761880-d075-11eb-98b4-5ca78473d77c.png)
![image](https://user-images.githubusercontent.com/32242507/122604080-a8ff8080-d075-11eb-9e3d-4ce966036c1e.png)
![image](https://user-images.githubusercontent.com/32242507/122604146-c59bb880-d075-11eb-9469-04142c48a83f.png)
![image](https://user-images.githubusercontent.com/32242507/122604177-d3513e00-d075-11eb-9169-6217bec825ce.png)
![image](https://user-images.githubusercontent.com/32242507/122604209-dfd59680-d075-11eb-885d-261101e4db22.png)

Thanks again for your help!

**Comment by BenPyton** [comment]
Thank you for the details, it helps me a lot :)
Did you tried to check the ReturnValue of the ContinueToAddRoom function ?
If this does not help you, then can you give me a minimal repro project ? (or your project directly if it isn't too big and you don't mind sharing it)

**Comment by CheddarBear** [comment]
I had the exact same print log when mine crashed, but it turns out i missed a step in the room creation so check if you added the corresponding level to your level parameter in the room data.
![image](https://user-images.githubusercontent.com/58309650/126490735-0119b9d5-da7f-46bc-b806-8efe62ecf47b.png)

**Comment by WiseMatthack** [comment]
> I had the exact same print log when mine crashed, but it turns out i missed a step in the room creation so check if you added the corresponding level to your level parameter in the room data.
> ![image](https://user-images.githubusercontent.com/58309650/126490735-0119b9d5-da7f-46bc-b806-8efe62ecf47b.png)

I double checked that, but it still crashes... :(

**Comment by WiseMatthack** [comment]
> Sorry for the late reply...
> Thank you for the details, it helps me a lot :)
> Did you tried to check the ReturnValue of the ContinueToAddRoom function ?
> If the return value of this function is always false, then it will never generate the dungeon (only the first room).
> If this does not help you, then can you give me a minimal repro project ? (or your project directly if it isn't too big and you don't mind sharing it to me).

I'm very sorry for the late answer too! I've been really busy recently...
Here are my project files:
[https://drive.google.com/drive/folders/1oO7kNGX32peWcy8Di_3exTRLesv6fELl?usp=sharing](https://drive.google.com/drive/folders/1oO7kNGX32peWcy8Di_3exTRLesv6fELl?usp=sharing)

**Comment by Acroviu** [comment]
> > Sorry for the late reply...
> > Thank you for the details, it helps me a lot :)
> > Did you tried to check the ReturnValue of the ContinueToAddRoom function ?
> > If the return value of this function is always false, then it will never generate the dungeon (only the first room).
> > If this does not help you, then can you give me a minimal repro project ? (or your project directly if it isn't too big and you don't mind sharing it to me).
> 
> I'm very sorry for the late answer too! I've been really busy recently...
> Here are my project files:
> https://drive.google.com/drive/folders/1oO7kNGX32peWcy8Di_3exTRLesv6fELl?usp=sharing

I just fix your problem, you need to create a variable for the end room using different Data or it will crash:
https://we.tl/t-09atG8CBIm
I don't have space on my drive, the link will only be available for 7 days
Hope this is helpful

**Comment by BenPyton** [comment]
Sorry for the too late reply, I didn't have the time to work on it...

I published [a new release](https://github.com/BenPyton/ProceduralDungeon/releases/tag/v1.2.2) where I fixed the crashes, and instead log some explicit errors.

Your issue was you returned None in ChooseFirstRoomData (you linked your SpawnRoom variable to the return node of this function, but you didn't set it to a value other than None)

So to fix your issue you just need to fill your variables in your DungeonGenerator actor.
