### ISSUE TITLE
Destroy Navmesh

### ISSUE THREAD

**Issue by Acroviu** [BenPyton/ProceduralDungeon#8]
Hi, I send you this problem on youtube, but I think it's easier to understand it after watching the pictures.

The Navmesh is in the persistent level and also in the level stream. It seems like the plugin its eating it up. 
![image](https://user-images.githubusercontent.com/31868722/130311282-01a3b984-65b9-491d-9e76-1e8ed79fcc45.png)

But if I make the Navmesh bigger it spawn correctly on top of the level
![image](https://user-images.githubusercontent.com/31868722/130311296-09641beb-3a8a-4ebb-8267-2741666e7b0a.png)

https://user-images.githubusercontent.com/31868722/130311562-1ce54a00-1e33-4d1c-96c1-b7e686cc6b29.mp4

It's like there's some reminiscence of information on the persistence level of the fail spawns.

**Comment by BenPyton** [comment]
Hi Acroviu,

Thank you for taking the time to explain your issue :)

The Navmesh should be rebuilt at the end of the generation, so the previous navmesh is replaced with a new one.
Indeed, In a 4.26 project, the navmesh is not rebuild correctly, I will investigate that...
(Maybe I forgot some settings to change for the Navmesh)

Also, I don't understand what you want are meaning by a "bigger" navmesh ?

**Comment by BenPyton** [comment]
Did you have the navmesh rebuild set to dynamic in the project settings ?
![image](https://user-images.githubusercontent.com/13402355/130332355-843ab8d0-8342-406b-b5cd-0f404d66c417.png)

**Comment by Acroviu** [comment]
> Hi Acroviu,
> 
> Thank you for taking the time to explain your issue :)
> 
> The Navmesh should be rebuilt at the end of the generation, so the previous navmesh is replaced with a new one.
> Indeed, In a 4.26 project, the navmesh is not rebuilding correctly, I will investigate that...
> (Maybe I forgot some settings to change for the Navmesh)
> 
> Also, I don't understand what you want are meaning by a "bigger" navmesh?

Sorry for the vague term "bigger". I make my z Scale bigger and that is when the navmesh spawns on the ceiling.
 
![image](https://user-images.githubusercontent.com/31868722/130337182-f4df2cc5-ae8e-4965-91d8-15b39e6c09b5.png)

and the navmesh is on "Movable" 
I found a way around the problem by adding a plane 100 points above Z and the navmesh spawns just fine. It seems it's only affecting the surface of the box brush in that specific Z-axis spawn point. I don't even need to use the execute console command rebuild navmesh to make it work. 

I hope this is helpful.

**Comment by BenPyton** [comment]
Sorry, I think I don't understand correctly what you are saying... ^^"

From your video, it seems you have a plane in your persistent level on wich the navmesh build on, what is the reason for that ?
Also, do you really need the navmesh to spawn on movable ? Generally, Navmesh are on static meshes, and the movables are set as obstacles (retriggering the build of only one chunk of the navmesh)

I tested on a sample project, and I have no issue with the navmesh generation (I don't have a plane with the navmesh in my persistant level, and the grounds of my rooms are set to static) so it seems there some settings in your project that produce this issue.
If you can share with me a minimal project to allow me reproduce your issue (or share with me your project if you can't create a minimal project, and if you can share it with me, and if not too big, max 500 MB) I will be able to investigate further your issue.

What I can say to you for sure, is that hte navmesh is forced to rebuild at the end of the generation (similar to executing the console command "Rebuild Navigation")

Also, sorry but I have not much experience with navmesh in Unreal... So I can't help you much more with the settings...

**Comment by gradusgl** [comment]
Place in each level Nav Mesh Bounds Volume.
Use in project settings  Runtime Generation - Dynamic
Add in your pawn and AI pawn  NavigationInvoker component.
![333](https://user-images.githubusercontent.com/23531289/131257001-3453b63c-4266-4b06-a6d1-374d60ef5ff0.png)
![111](https://user-images.githubusercontent.com/23531289/131256934-dae49cdc-08c5-44dc-95a4-b83a19bdb7e1.png)
![222](https://user-images.githubusercontent.com/23531289/131257009-1e8df42d-77b4-4025-a358-b225a3ac4bb7.png)

**Comment by Acroviu** [comment]
> Sorry, I think I don't understand correctly what you are saying... ^^"
> 
> From your video, it seems you have a plane in your persistent level on wich the navmesh build on, what is the reason for that ?
> Also, do you really need the navmesh to spawn on movable ? Generally, Navmesh are on static meshes, and the movables are set as obstacles (retriggering the build of only one chunk of the navmesh)
> 
> I tested on a sample project, and I have no issue with the navmesh generation (I don't have a plane with the navmesh in my persistant level, and the grounds of my rooms are set to static) so it seems there some settings in your project that produce this issue.
> If you can share with me a minimal project to allow me reproduce your issue (or share with me your project if you can't create a minimal project, and if you can share it with me, and if not too big, max 500 MB) I will be able to investigate further your issue.
> 
> What I can say to you for sure, is that hte navmesh is forced to rebuild at the end of the generation (similar to executing the console command "Rebuild Navigation")
> 
> Also, sorry but I have not much experience with navmesh in Unreal... So I can't help you much more with the settings...

I try both methods, adding a navmesh on the persistence level and also in the individual streaming levels.
I make it movable because if not, the navmesh would not spawn in the area it needs to be. It doesn't rotate according to the level spawning direction on the persistence level. 

Thank you for trying it out, I needed to know if it was something with the plug-in or with my project. My file is bigger than 500 MB but I think I can try different things now that I know it's my project the one creating the issue. 
Thank your response!

**Comment by Acroviu** [comment]
> Place in each level Nav Mesh Bounds Volume.
> Use in project settings Runtime Generation - Dynamic
> Add in your pawn and AI pawn NavigationInvoker component.
> ![333](https://user-images.githubusercontent.com/23531289/131257001-3453b63c-4266-4b06-a6d1-374d60ef5ff0.png)
> ![111](https://user-images.githubusercontent.com/23531289/131256934-dae49cdc-08c5-44dc-95a4-b83a19bdb7e1.png)
> ![222](https://user-images.githubusercontent.com/23531289/131257009-1e8df42d-77b4-4025-a358-b225a3ac4bb7.png)

Thank you, I try the invokers but it's the same result. I need to investigate what is creating the issue.

**Comment by BenPyton** [comment]
Sorry for not being able to help you more...
I hope you'll fix your issue :)
In that case, can you consider sharing your fix here ? So I can add it in the wiki of the plugin ;)

**Comment by Acroviu** [comment]
> Sorry for not being able to help you more...
> I hope you'll fix your issue :)
> In that case, can you consider sharing your fix here ? So I can add it in the wiki of the plugin ;)

No worries, letting me know the plug-in is not the problem it's helpful enough! 
For sure, ill share it when I find the issue
